import { Metadata } from "next"

export const metadata: Metadata = {
    title: 'Backlog Gamers - Privacy Policy',
    description: 'Generated by create next app', 
  }
  

export default function PrivacyPolicy() {
    return (
        <h1>Privacy Policy</h1>
    )
}