import { Metadata } from "next"

export const metadata: Metadata = {
    title: 'Backlog Gamers - Terms',
    description: 'Generated by create next app', 
}
  

export default function PrivacyPolicy() {
    return (
        <h1>Terms and Conditions</h1>
    )
}